name: Ola Mundo
on: push
jobs:
  minha-tarefa:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Commit felipe galati"
      - name: Dizer ola
        run: echo "2º etapa commit"
      - name: Mostrar data e hora
        run: date
      - name: Quem fez commit
        run: echo "Commit feito por ${{ github.actor }}"
