name: Ola Mundo
on: push
jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Commit felipe galati"
      - name: Dizer ola
        run: echo "2º etapa commit"
